package net.rsprot.protocol.api.login

public enum class LoginDisconnectionReason {
    CHANNEL_EXCEPTION,
    CHANNEL_IDLE,
    CHANNEL_OUT_OF_DATE,
    CHANNEL_IP_LIMIT,
    CHANNEL_WRITE_FAILED,
    CHANNEL_UNKNOWN_PACKET,

    CONNECTION_EXCEPTION,
    CONNECTION_IDLE,
    CONNECTION_UNKNOWN_PACKET,
    CONNECTION_INVALID_STEP_AWAITING_BETA_RESPONSE,
    CONNECTION_INVALID_STEP_UNINITIALIZED,
    CONNECTION_INVALID_STEP_REQUESTED_PROOF_OF_WORK,
    CONNECTION_PROOF_OF_WORK_FAILED,
    CONNECTION_PROOF_OF_WORK_EXCEPTION,
    CONNECTION_GAME_LOGIN_DECODING_FAILED,
    CONNECTION_GAME_RECONNECT_FAILED,
    CONNECTION_SESSION_ID_MISMATCH,

    GAME_CHANNEL_INACTIVE,
}
